#!/bin/bash

date

set -x
set -e

rm -rf ~/.ssh/known_hosts


PEER_COUNT=$@
export VARS_FILE=./vars/gcp.yml

# autogenerate the role for creating the gcp vms
python3 utils/gcp/gcp.py  -p $PEER_COUNT  >  roles/create/tasks/main.yml

ansible-playbook create.yml

sleep 20

# autogenerate the ansible hosts file
python3 utils/gcp/ans_hosts.py > hosts

# autogenerate a /etc/hosts file, to be included in each gcp vm
python3 utils/gcp/etc_hosts.py > roles/common/files/hosts


eval `ssh-agent`

ansible-playbook  --key-file "~/.ssh/fabric"  standardize-gcp.yml
ansible-playbook  --key-file "~/.ssh/fabric"  common.yml
ansible-playbook  --key-file "~/.ssh/fabric"  --extra-vars "peer_count=\"$PEER_COUNT\""  build.yml


# autogenerate each playbook for packaging each fabric component, peerXorgY, ordererY, etc
python3 utils/package.py  -p $PEER_COUNT  -v $VARS_FILE

# autogenerate each playbook for starting (via systemd) each fabric component
python3 utils/start.py  -p $PEER_COUNT  -v $VARS_FILE


ssh-add ~/.ssh/fabric

# call each autogenerated ansible playbook for packaging each fabric component
./autogen_package.sh

# call each autogenerated ansible playbook for starting each fabric component
./autogen_start.sh


date
